title: <p align="center"> Godwin Paul Vincent </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/godwin-paul-vincent/">LinkedIn</a> |
  <a href="https://github.com/godwin3737">GitHub</a>
  
  <br>   
  Godwin Paul Vincent is a Technology Leader , Generative AI (Azure Open AI GPT) and Conversational AI expert,  currently working as Senior General Manager in Schneider Electric. Responsible for the Product strategy, Pipeline, Innovation, Risk Management, Opportunity Framing, Engineering excellence and Agile Delivery.
  <br>
  Passionate Hands-on engineer , expert in .Net, Cloud Design Patterns, Automation (CI/CD), DevOps, Office 365, Azure, Microsoft Bot Framework, IoT, Microsoft Cognitive Services and Microsoft SharePoint.  As a engineering lead, have managed multiple projects and teams, passionate towards innovation, innovative teams and efficiency.
  <br>
  </p>



theme: jekyll-theme-minimal