title: <p align="center"> Godwin Paul Vincent </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/GodwinPaulVincent_CV_2023.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/godwin-paul-vincent/">LinkedIn</a> |
  <a href="https://github.com/godwin3737">GitHub</a>
  
  <br>   
  Godwin Paul Vincent is a Technology Leader , Generative AI (Azure Open AI GPT) and Conversational AI expert,  currently working as Senior General Manager in Schneider Electric. Responsible for the Product strategy, Pipeline, Innovation, Risk Management, Opportunity Framing, Engineering excellence and Agile Delivery.
  <br>
  </p>



theme: jekyll-theme-minimal